name: sa_academy_web
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dotted_line: ^3.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0-nullsafety.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/background.png

  - assets/images/code.jpg
  - assets/images/logo.png

  - assets/images/graduation.png
  - assets/images/smile.png
  - assets/images/school.png

  - assets/images/three-guys.png
  - assets/images/three-guys.png

  - assets/images/pencil.png
  - assets/images/briefcase.png
  - assets/images/pc.png
  - assets/images/party-popper.png

  - assets/images/unity-icon.png
  - assets/images/wpf-icon.png
  - assets/images/xamarin-icon.png

  - assets/images/calendar.png

  # faces
  - assets/images/faces/ak.png
  - assets/images/faces/dm.png
  - assets/images/faces/lm.png
  - assets/images/faces/as.png

  - assets/images/faces/mk.png
  - assets/images/faces/em.png
  - assets/images/faces/ac.png
  - assets/images/faces/tb.png

  - assets/images/faces/ez.png

  # updated 
  - assets/images/DISCORD-UPDATED.png
  - assets/images/UNITY-UPDATED.png
  - assets/images/WPF-UPDATED.png

  # after fixlist
  - assets/images/faq-icon.png
  - assets/images/email.png
  - assets/images/lockup.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: segoeui
       fonts:
        - asset: assets/fonts/SegoeUI/segoeui.ttf
          style: normal
        - asset: assets/fonts/SegoeUI/segoeuib.ttf
          weight: 700
        - asset: assets/fonts/SegoeUI/segoeuii.ttf
          style: italic

        - asset: assets/fonts/SegoeUI/segoeuil.ttf
          weight: 200
        - asset: assets/fonts/SegoeUI/segoeuisl.ttf
          weight: 300
        - asset: assets/fonts/SegoeUI/segoeuiz.ttf
          style: italic
          weight: 500

        - asset: assets/fonts/SegoeUI/seguibl.ttf
          weight: 800
        - asset: assets/fonts/SegoeUI/seguibli.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/SegoeUI/seguili.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/SegoeUI/seguisb.ttf
          weight: 600
        - asset: assets/fonts/SegoeUI/seguisbi.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/SegoeUI/seguisli.ttf
          weight: 300
          style: italic
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
